### ISSUE TITLE
Observable doesn't trigger compose for computed properties

### ISSUE THREAD

**Issue by pnewell** [skiptools/skip-model#1]
Computed properties within an Observable class do not trigger recomposition of views when changed. The following code works fine in iOS (any time the ItemList class updates its items array, the view updates as well), but does not trigger recomposition on Android.

Also, in my use case I actually have an array of ItemList that I am flat mapping in the computed property, but I simplified that for this example. Mentioning it because Arrays have also caused Observation issues in the past (that you all have fixed since).

```swift
public struct ContentView: View {
    @State var model = MyModel()
    
    public init() {
    }

    public var body: some View {
        VStack {
            ForEach(model.items) { item in
                Text(item.title)
            }
        }
    }
}

@Observable
public class MyModel {
    private var itemList: ItemList = ItemList()
    public var items: [Item] {
        self.itemList.items
    }

  // COMMENT: MY ACTUAL CODE
  // private var itemLists: [ItemList] = [ItemList()]
  // public var items: [Item] {
        // self.itemLists.flatMap(\.items)
  // }
}

@Observable
public class ItemList {
    var items: [Item] = []
    
    init() {
        Task {
            try await Task.sleep(nanoseconds: 100_000_00)
            self.items = [Item(id: UUID(), title: "First")]
        }
        
    }
}

public struct Item: Identifiable {
    public let id: UUID
    public var title: String
}
```

**Comment by bspringston** [comment]
try using @StateObject when working with classes:
@StateObject var model = MyModel()

**Comment by aabewhite** [comment]
Thanks for the report! We'll definitely take a look

**Comment by pnewell** [comment]
@aabewhite After some more analysis, this doesn't appear to be an issue with computed properties (those seems to work fine in other scenarios), but instead is an issue with nested Observable classes.

As an example, this simpler example also does not properly update in Android but does in iOS:

```
@Observable
class NestedObservable {
    var title: String = ""
}

@Observable
class Repository {
    var nested: NestedObservable = NestedObservable()
    
    func setNestedTitle() {
        self.nested.title = Date().description
    }
}

public struct ContentView: View {
    @State var repo: Repository = Repository()
    
    public var body: some View {
        VStack {
            Text(repo.nested.title)
            Button(action: { repo.setNestedTitle() }) {
                Text("Set Nested Title")
            }
        }
    }
}
```

**Comment by aabewhite** [comment]
Thanks! Will look into this over the weekend

**Comment by aabewhite** [comment]
This has been fixed in the latest skip, skip-model, and skip-ui releases (0.7.47, 0.4.1, and 0.4.4). Thanks again, and please let us know if you run into any issues.
